#!/bin/bash
set -e

# Change to the project directory
cd /opt/dolianova
# Pull the latest changes from the repository
git pull
# Activate the virtual environment
source .venv/bin/activate

# Run the water_system_controller.py script
python water_system_controller.py
